# Default values for scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  enable: true
  name: crane-scheduler
  image:
    repository: docker.io/gocrane/crane-scheduler
    tag: 0.1.23
  replicaCount: 1

controller:
  enable: true
  name: crane-scheduler-controller
  image:
    repository: docker.io/gocrane/crane-scheduler-controller
    tag: 0.0.23
  replicaCount: 1

global:
  prometheusAddr: http://prometheus-server.crane-system.svc.cluster.local:8080
